import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'
import { useRef } from 'react'

export default function Home() {
  const emailInput = useRef()
  async function sendEmail() {
    console.log('Sending an email to', emailInput.current.value)
    const { data } = await axios.post('/api/sendgrid', { email: emailInput.current.value })
    console.log('Response', data)
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Test Sendgrid
        </h1>

        <div className={styles.grid}>
          <div  className={styles.card}>
            <h2>Send Test Email</h2>
            <input ref={emailInput} placeholder="Enter your email..." />
            <button onClick={sendEmail}>Send &rarr;</button>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
